# Generated by Django 2.2.7 on 2019-12-02 16:44

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.TextField(verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(max_length=2, validators=[django.core.validators.MinValueValidator(0)], verbose_name='edad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ingreso_sistema',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ingreso_sistema'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=12, verbose_name='telefono'),
        ),
    ]
