# Generated by Django 2.2.7 on 2019-12-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20191202_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(help_text='Ingrese numero positivo', max_length=2, verbose_name='edad'),
        ),
    ]
