# Generated by Django 2.2.7 on 2019-12-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20191202_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(help_text='Ingrese numero positivo', verbose_name='edad'),
        ),
    ]
